package com.deval.gestiondestock.utils;

public interface Constants {
    public static String APP_ROOT = "gestiondestock/v1";
    String COMMANDE_FOURNISSEURS_ENDPOINT = APP_ROOT + "/CommandeFournisseurs/";
    String ENTREPRISE_ENDPOINT = APP_ROOT + "/entreprises";

    String FOURNISSEUR_ENDPOINT = APP_ROOT + "/fournisseurs";
    String UTILISATEURS_ENDPOINT = APP_ROOT + "/utilisateurs";
    String VENTES_ENDPOINT = APP_ROOT + "/ventes";

    String AUTHENTIFICATION_ENDPOINT = APP_ROOT + "/auth";

    String CREATE_COMMANDE_FOURNISSEURS_ENDPOINT = COMMANDE_FOURNISSEURS_ENDPOINT + "/create";
    String FIND_COMMANDE_FOURNISSEURS_BY_ID_ENDPOINT = COMMANDE_FOURNISSEURS_ENDPOINT + "/{idCommandeFournisseur}";
    String FIND_COMMANDE_FOURNISSEURS_BY_CODE_ENDPOINT = COMMANDE_FOURNISSEURS_ENDPOINT + "/{codeCommandeFournisseur}";

    String FIND_ALL_COMMANDE_FOURNISSEURS_ENDPOINT = COMMANDE_FOURNISSEURS_ENDPOINT + "/all";
    String DELETE_COMMANDE_FOURNISSEURS_ENDPOINT = COMMANDE_FOURNISSEURS_ENDPOINT + "/delete/{idCommandeFournisseur}";




    String CREATE_ENTREPRISE_ENDPOINT = ENTREPRISE_ENDPOINT + "/create";

    String FIND_ENTREPRISE_BY_ID_ENDPOINT = ENTREPRISE_ENDPOINT + "/{idEntreprise}";

    String FIND_ALL_ENTREPRISE_ENDPOINT = ENTREPRISE_ENDPOINT + "/all";

    String DELETE_ENTREPRISE_ENDPOINT = ENTREPRISE_ENDPOINT + "/delete/{idEntreprise}";


    String CREATE_UTILISATEURS_ENDPOINT = UTILISATEURS_ENDPOINT + "/create";

    String FIND_UTILISATEURS_BY_ID_ENDPOINT = UTILISATEURS_ENDPOINT + "/{idUtilisateurs}";

    String FIND_UTILISATEURS_BY_NOM_ENDPOINT = UTILISATEURS_ENDPOINT + "/{nomUtilisateurs}";

    String FIND_UTILISATEURS_BY_NUM_TEL_ENDPOINT = UTILISATEURS_ENDPOINT + "/{numTelUtilisateurs}";

    String FIND_UTILISATEURS_BY_EMAIL_TEL_ENDPOINT = UTILISATEURS_ENDPOINT + "/{emailUtilisateurs}";

    String FIND_ALL_UTILISATEURS_ENDPOINT = UTILISATEURS_ENDPOINT + "/all";

    String DELETE_UTILISATEURS_ENDPOINT = UTILISATEURS_ENDPOINT + "/delete/{idUtilisateurs}";



    String CREATE_VENTES_ENDPOINT = VENTES_ENDPOINT + "/create";

    String FIND_VENTES_BY_ID_ENDPOINT = VENTES_ENDPOINT + "/{idVentes}";

    String FIND_VENTES_BY_CODE_ENDPOINT = VENTES_ENDPOINT + "/{code}";

    String FIND_ALL_VENTES_ENDPOINT = VENTES_ENDPOINT + "/all";

    String DELETE_VENTES_ENDPOINT = VENTES_ENDPOINT + "/delete/{idVentes}";
}
